// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

// Account
type PreGoCrmUserC struct {
	// Account ID
	UsrID uint32
	// Email
	UsrEmail string
	// Phone Number
	UsrPhone string
	// User name
	UsrUsername string
	// Password
	UsrPassword string
	// PCreation time
	UsrCreatedAt int32
	// Update time
	UsrUpdateAt int32
	// Creation IP
	UsrCreateIpAt string
	// last login time
	UsrLastLoginAt int32
	// Last Login IP
	UsrLastLoginIpAt string
	// Login times
	UsrLoginTimes int32
	// Status 1:enable, 0:disable, -1:deleted
	UsrStatus bool
}
