// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/dinos/go-ecommerce-be-api/internal/controllers"
	"github.com/dinos/go-ecommerce-be-api/internal/repo"
	"github.com/dinos/go-ecommerce-be-api/internal/service"
)

// Injectors from user.wire.go:

func InitUserRouterHandle() (*controllers.UserController, error) {
	iUserRepo := repo.NewUserRepo()
	iUserAuthRepo := repo.NewUserAuthRepo()
	iUserService := service.NewUserService(iUserRepo, iUserAuthRepo)
	userController := controllers.NewUserController(iUserService)
	return userController, nil
}
