basePath: /v1/2024
definitions:
  model.RegisterInput:
    properties:
      verify_key:
        type: string
      verify_purpose:
        type: string
      verify_type:
        type: integer
    type: object
  response.ErrorResponse:
    properties:
      code:
        type: integer
      detail: {}
      error:
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: localhost:8002
info:
  contact:
    email: congdoan99tm@gmail.com
    name: TEAM TIPSGO
    url: github.com/congdoan99tm/go-ecomerce
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: github.com/congdoan99tm/go-ecomerce
  title: API Documentation Ecomerrce Backend SHOPDEVGO
  version: "1.0"
paths:
  /user/register:
    post:
      consumes:
      - application/json
      description: When user is registered send otp to email
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/model.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: User Registration
      tags:
      - accounts management
swagger: "2.0"
