// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGoCrmUser = "go_crm_user"

// GoCrmUser Account
type GoCrmUser struct {
	UsrID            int32  `gorm:"column:usr_id;primaryKey;autoIncrement:true;comment:Account ID" json:"usr_id"`                 // Account ID
	UsrEmail         string `gorm:"column:usr_email;not null;comment:Email" json:"usr_email"`                                     // Email
	UsrPhone         string `gorm:"column:usr_phone;not null;comment:Phone Number" json:"usr_phone"`                              // Phone Number
	UsrUsername      string `gorm:"column:usr_username;not null;comment:User name" json:"usr_username"`                           // User name
	UsrPassword      string `gorm:"column:usr_password;not null;comment:Password" json:"usr_password"`                            // Password
	UsrCreatedAt     int32  `gorm:"column:usr_created_at;not null;comment:PCreation time" json:"usr_created_at"`                  // PCreation time
	UsrUpdateAt      int32  `gorm:"column:usr_update_at;not null;comment:Update time" json:"usr_update_at"`                       // Update time
	UsrCreateIPAt    string `gorm:"column:usr_create_ip_at;not null;comment:Createion IP" json:"usr_create_ip_at"`                // Createion IP
	UsrLastLoginAt   int32  `gorm:"column:usr_last_login_at;not null;comment:last login time" json:"usr_last_login_at"`           // last login time
	UsrLastLoginIPAt string `gorm:"column:usr_last_login_ip_at;not null;comment:Last Login IP" json:"usr_last_login_ip_at"`       // Last Login IP
	UsrLoginTimes    int32  `gorm:"column:usr_login_times;not null;comment:Login times" json:"usr_login_times"`                   // Login times
	UsrStatus        bool   `gorm:"column:usr_status;not null;comment:Status 1:enable, 0:disnable, -1:deleted" json:"usr_status"` // Status 1:enable, 0:disnable, -1:deleted
}

// TableName GoCrmUser's table name
func (*GoCrmUser) TableName() string {
	return TableNameGoCrmUser
}
